### PR TITLE
Create another from create page

### PR DESCRIPTION
**Pull request by a21ns1g4ts**

### CODE REVIEW

**Comment by awcodes** [comment]
Can you test this with Simple Resources? I have a feeling that it will break since Simple Resources don't have 'Create Pages'.

**Comment by a21ns1g4ts** [comment]
Ok. I will test.

**Comment by a21ns1g4ts** [comment]
I really shouldn’t always rely on the create page. I’m not sure if the best approach is to ignore it when it doesn’t exist and assume the default as true. What do you think about this?
` ->createAnother(isset($r->getPages()['create']) ? $r->getPages()['create']->getPage()::canCreateAnother() : true);`

**Comment by awcodes** [comment]
Are you trying to disable create another?

**Comment by a21ns1g4ts** [comment]
Yep. Is there a way to do it?"

**Comment by awcodes** [comment]
Ok. Got this working but now the question is should it just be a global setting or inspect from the resource or both?

**Comment by a21ns1g4ts** [comment]
What do you think of keeping CreateRecord default to true but adding a global setting, like filament-quick-create.can-create-another? We could also have:

php
Copiar código
QuickCreatePlugin::make()
    ->canCreateAnother(fn(...) => ...)

**Comment by a21ns1g4ts** [comment]
Thank you; I was about to propose the change you just made. Thanks again.

**Pull request closed without merging**
